run:
  concurrency: 12
  timeout: 1m
  issues-exit-code: 1
  tests: true
  modules-download-mode: vendor
  allow-parallel-runners: true
linters:
  disable-all: true
  enable:
    # complexity
    - gocognit
    - cyclop
    - funlen
    # bugs
    - noctx
    - errcheck
    - gosec
    - staticcheck
    # performance
    - govet
    - prealloc
    # code style + cleanup
    - revive
    - dupl
    - ineffassign
    - unconvert
    - goconst
    - nakedret
    - misspell
    - unused
    - unparam
    - gocritic
    - depguard
    # formatters
    - goimports
linters-settings:
  gosec:
    excludes:
      - G112
  gocognit:
    min-complexity: 25
  cyclop:
    max-complexity: 25
    package-average: 0.0
    skip-tests: false
  funlen:
    lines: 130
    statements: 100
  errcheck:
    check-type-assertions: true
    check-blank: false
  govet:
    enable-all: true
    check-shadowing: true
  prealloc:
    simple: true
    range-loops: true
    for-loops: false
  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      - name: line-length-limit
        arguments: [ 180 ]
      - name: function-result-limit
        arguments: [ 3 ]
      - name: argument-limit
        arguments: [ 6 ]
      - name: blank-imports
      - name: error-return
      - name: increment-decrement
      - name: deep-exit
      - name: var-declaration
      - name: package-comments
      - name: dot-imports
      - name: exported
      - name: unreachable-code
      - name: waitgroup-by-value
      - name: early-return
      - name: indent-error-flow
      - name: range
      - name: errorf
      - name: error-naming
      - name: error-strings
      - name: receiver-naming
      - name: unexported-return
      - name: time-naming
      - name: context-keys-type
      - name: context-as-argument
      - name: defer
      - name: nested-structs
      - name: var-naming
        arguments: [
          ["ID", "HTTP", "GUID", "UUID", "SQL", "SSH", "JSON", "API"],
          ["URL", "DB"]
        ]
  dupl:
    threshold: 150
  goconst:
    min-len: 5
    min-occurrences: 3
    ignore-tests: true
    numbers: true
    match-constant: true
    ignore-calls: true
  misspell:
    locale: US
  unused:
    go: "1.15"
  depguard:
    list-type: blacklist
    include-go-root: false
    packages: [ "github.com/lib/pq" ]
    packages-with-error-message: []
  gofmt:
    simplify: true